apiVersion: v1
kind: Service
metadata:
  name: {{ include "root-container-checker.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: root-container-checker
spec:
  selector:
    app: root-container-checker
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: {{ .Values.service.type }}