apiVersion: v1
kind: ServiceAccount
metadata:
  name: root-container-checker-sa
  namespace: root-container-checker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: root-container-checker-sa-binding
subjects:
- kind: ServiceAccount
  name: root-container-checker-sa
  namespace: root-container-checker
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
