apiVersion: v1
kind: Service
metadata:
  name: root-container-checker
  namespace: root-container-checker
spec:
  selector:
    app: root-container-checker
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP